import type { BrandConfig } from "@/types/brand";
export const BRAND: BrandConfig = {
  businessName: "DHANALEKSHMI JEWELLERY",
  tagline: "Fine Gold, Diamond & Silver Jewellery in Attingal",
  description: "DHANALEKSHMI JEWELLERY is Attingal's trusted destination for gold, diamond and silver jewellery. Serving Attingal and surrounding areas in Kerala with exquisite craftsmanship and timeless designs for every celebration.",
  logo: "/icons/logo.svg",
  favicon: "/favicon.ico",
  heroVideo: "https://res.cloudinary.com/fylz5e3j/video/upload/v1782936959/VN20260702_013328_tbexfn.mp4",
  storyVideos: [
    { quote: "ലാളിത്യത്തിലെ പൂർണ്ണത.", description: "അണിയാൻ തീരെ ഭാരമില്ലാത്ത, എന്നാൽ കണ്ണഞ്ചിപ്പിക്കുന്ന ഡിസൈനുകൾ. നിങ്ങളുടെ ഓരോ സാധാരണ ദിവസത്തെയും മനോഹരമാക്കാൻ ഇവ മതിയാകും.", video: "https://res.cloudinary.com/fylz5e3j/video/upload/v1782936959/VN20260702_013328_tbexfn.mp4", segments: { startAt: 0, loopEnd: 8 } },
    { quote: "കൈകളിൽ വിരിയുന്ന വിസ്മയം.", description: "ഓരോ ആഭരണവും ഓരോ കലാരൂപമാണ്. അതിസൂക്ഷ്മമായി, തികഞ്ഞ പൂർണ്ണതയോടെ രൂപപ്പെടുത്തിയെടുത്തവ. നിങ്ങളുടെ സ്വപ്നങ്ങൾക്ക് സ്വർണ്ണത്തിൽ ജീവൻ വയ്ക്കുമ്പോൾ.", video: "https://res.cloudinary.com/fylz5e3j/video/upload/v1782936959/VN20260702_013328_tbexfn.mp4", segments: { startAt: 32, loopEnd: 40 } },
    { quote: "അറ്റിങ്ങലിൻ്റെ ഹൃദയത്തിൽ നിന്ന്.", description: "ഈ നാടിൻ്റെ പൈതൃകവും പുതുമയും ഒത്തുചേരുന്ന ആഭരണങ്ങൾ. തലമുറകളായി നിങ്ങൾ നൽകുന്ന വിശ്വാസത്തിന് സ്വർണ്ണത്തേക്കാൾ തിളക്കമുണ്ട്.", video: "https://res.cloudinary.com/fylz5e3j/video/upload/v1782936959/VN20260702_013328_tbexfn.mp4", segments: { startAt: 16, loopEnd: 24 } },
  ],
  storeImages: [
    "https://res.cloudinary.com/sqsrrir4/image/upload/v1785497487/attingal/dhanalekshmi-jewellery-kizhakkupuram/store1.webp",
    "https://res.cloudinary.com/sqsrrir4/image/upload/v1785497489/attingal/dhanalekshmi-jewellery-kizhakkupuram/store2.webp",
    "https://res.cloudinary.com/fylz5e3j/image/upload/v1782940196/hayazcc_vuguic.webp",
    "https://res.cloudinary.com/fylz5e3j/image/upload/v1782940196/hayazbb_wb1juf.webp"
  ],
  address: "Kizhakkupuram, Thiruvananthapuram, Attingal, Kerala 695101",
  city: "Attingal",
  state: "Kerala",
  pincode: "695101",
  phone: "+919447206172",
  whatsapp: "919447206172",
  email: "",
  mapsLink: "https://www.google.com/maps/place/?q=place_id:ChIJ3ch4z4rpBTsRst2TaqxzaHU",
  openingHours: "Mon–Sat: 9:30 AM – 8:00 PM · Sunday: 10:00 AM – 7:00 PM",
  instagram: "",
  facebook: "",
  seo: {
    title: "DHANALEKSHMI JEWELLERY | Gold & Jewellery in Attingal, Kerala",
    description: "DHANALEKSHMI JEWELLERY is Attingal's trusted destination for gold, diamond and silver jewellery. Serving Attingal and surrounding areas in Kerala with exquisite",
    keywords: ["DHANALEKSHMI JEWELLERY", "jewellery Attingal", "gold jewellery Attingal", "gold Attingal Kerala", "jewellery store Kerala"],
    canonical: "https://dhanalekshmi-jewellery-kizhakkupuram-project-z3.vercel.app",
    ogImage: "https://res.cloudinary.com/sqsrrir4/image/upload/v1785497487/attingal/dhanalekshmi-jewellery-kizhakkupuram/store1.webp",
  },
  faq: [],
  whatsappMessage: "Hello DHANALEKSHMI JEWELLERY, I'd like to know more about your jewellery collections.",
};
